apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ibpgzx67a-go 
  janus-idp.io/tekton: ibpgzx67a-go
  backstage.io/kubernetes-id: ibpgzx67a-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ibpgzx67a-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml